package com.example.dynamodbpetsdemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.boot.context.properties.bind.DefaultValue;

import java.beans.Transient;

@Data
@DynamoDBTable(tableName="Pets")
public class Pet {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private int age;

    private int dogAge;

    public Pet() {
    }

    public Pet(String id, String name, int age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    /*
    @Override
    public boolean equals(Object obj) {
        //compare passed object and current object reference
        if(this == obj) {
            return true;
        }

        if(obj instanceof Pet) {
            Pet p = (Pet) obj;
            if((this.id.equals(p.id)) && (this.name.equals(p.name)) && (this.age == p.age)) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

     */
}
